### ISSUE TITLE
Drop in replacement for electron-prebuilt?

### ISSUE THREAD

**Issue by TimNZ** [electron-userland/electron-prebuilt-compile#16]
Is this supposed to be a drop in replacement for electron-prebuilt?

I am running './node_modules/bin/electron' and getting:

```
App threw an error during load
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at main (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/electron-prebuilt-compile/lib/es6-init.js:31:35)
    at Object.<anonymous> (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/electron-prebuilt-compile/lib/es6-init.js:41:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/electron-prebuilt-compile/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:288:12)
```

Running './node_modules/.bin/electron index.js' I get:

```
App threw an error during load
Error: Couldn't find preset "stage-0" relative to directory "/Users/timshnaider/Desktop/Development/electron/splitter-test"
    at /Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at BabelCompiler.compileSync (/Users/timshnaider/Desktop/Development/electron/splitter-test/node_modules/electron-compilers/lib/js/babel.js:129:19)
```

**Comment by TimNZ** [comment]
.compilerc appears to be mandatory
