### ISSUE TITLE
cannot find 'acorn' module

### ISSUE THREAD

**Issue by kounelios13** [electron-userland/electron-prebuilt-compile#50]
Hello.After updating to version 1.7.8 I encountered the following error:

```
Failed to compile /home/kounelios/Documents/GitHub/UGSM/src/public/views/index.jade: Cannot find module 'acorn'
Error: Cannot find module 'acorn'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/kounelios/Documents/GitHub/UGSM/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kounelios/Documents/GitHub/UGSM/node_modules/constantinople/index.js:3:13)
    at Object.<anonymous> (/home/kounelios/Documents/GitHub/UGSM/node_modules/constantinople/index.js:102:3)
    at Module._compile (module.js:571:32)
    at Object.require.extensions.(anonymous function) [as .js] (/home/kounelios/Documents/GitHub/UGSM/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
```

Any ideas what caused it?

**Comment by alisonmoura** [comment]
I'm having this problem too 😅
